version: '3'
services:
  roster-scrapper:
    build: .
    command: python pipeline/roster_scrapper.py
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
  games-scrapper:
    build: .
    command: python pipeline/games_results_scrapper.py
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
  checker:
    build: .
    command: python pipeline/watchdog_checker.py
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
